### ISSUE TITLE
Something wrong in Windows 7 

### ISSUE THREAD

**Issue by yzpopulation** [Tampermonkey/tamperdav#6]
``` bash
call npm install
npm WARN tamperdav@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 2134 packages in 2.661s
found 0 vulnerabilities

server is listening on 7000
fs.js:121
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:516:3)
    at tryReadSync (fs.js:339:20)
    at Object.readFileSync (fs.js:376:19)
    at get (G:\tamperdav-master\server.js:126:29)
    at Server.requestHandler (G:\tamperdav-master\server.js:472:16)
    at Server.emit (events.js:188:13)
    at parserOnIncoming (_http_server.js:676:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
```

**Comment by derjanb** [comment]
This is working fine here. Maybe a configration error?

**Comment by derjanb** [comment]
Hmm, I can reproduce the issue by accessing "http://localhost:7000/" via browser, which is not what TamperDAV is designed for. What are you trying to do? What is your WebDAV client?

**Comment by yzpopulation** [comment]
Sorry, I mistakenly thought it supports web access.
